### ISSUE TITLE
Getting a silent error with csvtojson

### ISSUE THREAD

**Issue by cgmorgenstern** [watson-developer-cloud/tradeoff-analytics-nodejs#22] opened 2015-11-30 12:41 UTC
When trying the demo with my own data, the button "show visualization" silently fails in the CSVtoJSON page, even though the data is correctly displayed in the table and I chose objectives to maximize. My dev console in Firefox prints the error "$scope.resolution is undefined" and a bit of stack trace.

Here is my test data (added .txt for upload):
[regional_averages_rr_01.csv.txt](https://github.com/watson-developer-cloud/tradeoff-analytics-nodejs/files/47282/regional_averages_rr_01.csv.txt)

**Comment by germanattanasio** [comment] 2015-12-05 03:39
The problem is not in this project, it's in the http://tradeoff-analytics-csvtojson.mybluemix.net/ application. I will keep this issue open until we fix the issue in the other app.

**Comment by rotemah** [comment] 2015-12-06 06:26
We fixed the silent error. There is a limit of 10 objectives, and the data had 20.

**Comment by germanattanasio** [comment] 2015-12-06 06:28
I'm closing this since the issue was fixed.

**Closed by germanattanasio** 2015-12-06 06:28 UTC
